[package]
authors = ["Michael Lodder <redmike7@gmail.com>"]
categories = ["cryptography"]
description = """
Pure Rust implementation of XMSS (eXtended Merkle Signature Scheme)
as described in RFC 8391 and SP 800-208
"""
edition = "2024"
homepage = "https://github.com/mikelodder7/pq-xmss"
keywords = ["xmss", "signature", "crypto", "cryptography", "rfc8391"]
license = "Apache-2.0 OR MIT"
name = "pq-xmss"
readme = "README.md"
repository = "https://github.com/mikelodder7/pq-xmss"
rust-version = "1.85"
version = "0.1.2"

[package.metadata.docs.rs]
all-features = true

[[bench]]
harness = false
name = "signing"
required-features = ["extra-depths"]

[features]
alloc = []
default = ["std"]
extra-depths = []
pkcs8 = ["dep:pkcs8", "dep:spki", "dep:der", "dep:const-oid"]
serde = ["dep:serdect"]
std = ["alloc", "rand/std", "rand/std_rng", "rand/sys_rng", "rand/thread_rng", "subtle/std", "thiserror/std"]

[dependencies]
const-oid = { optional = true, version = "0.10" }
der = { default-features = false, features = ["alloc"], optional = true, version = "0.8" }
digest = "0.11"
hybrid-array = { features = ["zeroize"], version = "0.4" }
pkcs8 = { default-features = false, features = ["alloc"], optional = true, version = "0.11" }
rand = { default-features = false, version = "0.10" }
serdect = { features = ["alloc"], optional = true, version = "0.4" }
sha2 = "0.11"
shake = "0.1"
signature = "3"
spki = { default-features = false, features = ["alloc"], optional = true, version = "0.8" }
subtle = { default-features = false, features = ["i128"], version = "2.6" }
thiserror = { default-features = false, version = "2" }
zeroize = "1"

[dev-dependencies]
postcard = { features = ["alloc"], version = "1" }
serde_json = "1"

[lints.rust]
missing_debug_implementations = "deny"
missing_docs = "deny"
trivial_casts = "deny"
trivial_numeric_casts = "deny"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)', 'cfg(docsrs)'] }
unsafe_code = "deny"
unstable_features = "deny"
unused_extern_crates = "deny"
unused_import_braces = "deny"
unused_lifetimes = "deny"
unused_parens = "deny"
unused_qualifications = "deny"

[lints.clippy]
cast_possible_truncation = "warn"
cast_possible_wrap = "warn"
cast_precision_loss = "warn"
cast_sign_loss = "warn"
checked_conversions = "warn"
mod_module_files = "warn"
panic = "warn"
panic_in_result_fn = "warn"
unwrap_used = "deny"
